name: C/C++ CI

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ testing ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make

